# LuccaSecurityBundle Routing - basic
lucca_security_bundle_basic:
    resource: "@LuccaSecurityBundle/Controller"
    type: attribute
    prefix: /{dep_code}/

# LuccaSecurityBundle Routing - admin
lucca_security_bundle_admin:
    resource: "@LuccaSecurityBundle/Controller/Admin"
    type: attribute
    prefix: /{dep_code}/back-office

# LuccaSecurityBundle Routing - sso
lucca_security_bundle_sso:
    resource: "@LuccaSecurityBundle/Controller/Sso"
    type: attribute
    prefix: /sso

# LuccaSecurityBundle Routing - rest api
lucca_security_bundle_rest_api:
    resource: "@LuccaSecurityBundle/Controller/RestApi"
    type: attribute
    prefix: /api/external
