## LuccaCoreBundle Configuration
lucca_core:
    asset_version: "%env(LUCCA_STRATEGY_ASSET_VERSION)%"
    asset_forceRefresh: "%env(LUCCA_STRATEGY_ASSET_FORCE_REFRESH)%"
    google_analytics_id: "%env(LUCCA_GOOGLE_ANALYTICS_ID)%"
    lucca_unit_test_dep_code: '%env(LUCCA_UNIT_TEST_DEP_CODE)%'
    aigle_api_base_url: '%env(AIGLE_API_BASE_URL)%'
    aigle_api_key: '%env(AIGLE_API_KEY)%'
    lucca_rest_api_key: '%env(LUCCA_REST_API_KEY)%'
