# LuccaFolderBundle Routing
lucca_minute_bundle_admin:
    resource: "@LuccaFolderBundle/Controller/Admin"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaFolderBundle Routing - Manual Editing
lucca_minute_bundle_manual_edit:
    resource: "@LuccaFolderBundle/Controller/ManualEdit"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaFolderBundle Routing - Printing
lucca_minute_bundle_printing:
    resource: "@LuccaFolderBundle/Controller/Printing"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaFolderBundle Routing - Dashboard
lucca_minute_bundle_dashboard:
    resource: "@LuccaFolderBundle/Controller/Dashboard"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaFolderBundle Routing - API
lucca_minute_bundle_api:
    resource: "@LuccaFolderBundle/Controller/Api"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaFolderBundle Routing - By Folder
lucca_minute_bundle_by_folder:
    resource: "@LuccaFolderBundle/Controller/ByFolder"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaFolderBundle Routing - Rest API
lucca_folder_bundle_rest_api:
    resource: "@LuccaFolderBundle/Controller/RestApi"
    type:     attribute
    prefix:   /api/external